### ISSUE TITLE
no captcha input  is shown and error when including line renderScripts(), 

### ISSUE THREAD

**Issue by abalakrishnan** [kutia-software-company/laravel-google-recaptcha#2]
$grecaptcha  = GRecaptcha::render([], false); with this i can generate the div in my blade but no captcha is being displayed And 
When i add this {!! \GRecaptcha::renderScripts() !!} in my blade file it throws error 
Access to undeclared static property: AstritZeqiri\GRecaptcha\GRecaptcha::$script ( path to my blade file)
I am working with php 7, Laravel 5.3 , vagrant/xampp environments. Could you please check this issue and give a solution to make it work

**Comment by astritzeqiri** [comment]
@abalakrishnan I made a new commit with the fix can you check it now.

**Comment by astritzeqiri** [comment]
@abalakrishnan can you check it now.

**Comment by abalakrishnan** [comment]
I have checked it after composer update.. now it work like a charm...  thank you!

**Comment by astritzeqiri** [comment]
You're welcome @abalakrishnan
